run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gocritic
    - errcheck
    - revive
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - gosec      # セキュリティチェック
    - bodyclose  # HTTP Bodyの閉じ忘れ防止
    - unused     # 未使用コードの削除
    - noctx      # context.Contextを引数に取る関数で、context.Contextを使用していない場合に警告
    - unparam     # 未使用の関数パラメータを検出
    - dupl        # 重複コードの検出
    - prealloc    # ループ内でのスライスの再割り当てを検出
    - makezero    # makeで初期化された変数がゼロ値である場合の警告

  exclude-use-default: false