// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddCertificatesToCRL(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:number):Promise<backend.CRLUpdateResult>;

export function Base64Decode(arg1:string,arg2:boolean):Promise<string>;

export function Base64Encode(arg1:string,arg2:boolean):Promise<string>;

export function CalculateBaseExpression(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<backend.BaseCalculationResult>;

export function CalculateCIDR(arg1:string):Promise<backend.CIDRCalculationResult>;

export function CalculateTransferTime(arg1:number,arg2:string,arg3:number,arg4:string):Promise<backend.TransferTimeResult>;

export function ConvertBaseValue(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<backend.BaseConversionResult>;

export function ConvertDataTransferRate(arg1:number,arg2:string):Promise<backend.DataTransferRateResult>;

export function ConvertUnit(arg1:number,arg2:string):Promise<backend.ConversionResult>;

export function ExtractPublicKey(arg1:string,arg2:string):Promise<string>;

export function GenerateMTLSCertificates(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:Array<string>,arg7:number,arg8:string):Promise<backend.MTLSCertificateResult>;

export function GenerateMTLSCertificatesMultiClient(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:Array<string>,arg7:Array<string>,arg8:number,arg9:string):Promise<backend.MTLSCertificatesMultiClientResult>;

export function GeneratePrivateKey(arg1:string):Promise<string>;

export function GenerateSelfSignedCertificate(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:string):Promise<backend.SelfSignedCertificateResult>;

export function JWTDecode(arg1:string):Promise<backend.JWTDecodeResult>;

export function JWTEncode(arg1:string,arg2:string,arg3:string):Promise<string>;

export function JWTVerify(arg1:string,arg2:string):Promise<backend.JWTDecodeResult>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function VerifyKeyPair(arg1:string,arg2:string,arg3:string):Promise<boolean>;
