// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCertificatesToCRL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCertificatesToCRL'](arg1, arg2, arg3, arg4, arg5);
}

export function Base64Decode(arg1, arg2) {
  return window['go']['main']['App']['Base64Decode'](arg1, arg2);
}

export function Base64Encode(arg1, arg2) {
  return window['go']['main']['App']['Base64Encode'](arg1, arg2);
}

export function CalculateBaseExpression(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CalculateBaseExpression'](arg1, arg2, arg3, arg4, arg5);
}

export function CalculateCIDR(arg1) {
  return window['go']['main']['App']['CalculateCIDR'](arg1);
}

export function CalculateTransferTime(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CalculateTransferTime'](arg1, arg2, arg3, arg4);
}

export function ConvertBaseValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertBaseValue'](arg1, arg2, arg3, arg4);
}

export function ConvertDataTransferRate(arg1, arg2) {
  return window['go']['main']['App']['ConvertDataTransferRate'](arg1, arg2);
}

export function ConvertUnit(arg1, arg2) {
  return window['go']['main']['App']['ConvertUnit'](arg1, arg2);
}

export function ExtractPublicKey(arg1, arg2) {
  return window['go']['main']['App']['ExtractPublicKey'](arg1, arg2);
}

export function GenerateMTLSCertificates(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['GenerateMTLSCertificates'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GenerateMTLSCertificatesMultiClient(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['GenerateMTLSCertificatesMultiClient'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function GeneratePrivateKey(arg1) {
  return window['go']['main']['App']['GeneratePrivateKey'](arg1);
}

export function GenerateSelfSignedCertificate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateSelfSignedCertificate'](arg1, arg2, arg3, arg4, arg5);
}

export function JWTDecode(arg1) {
  return window['go']['main']['App']['JWTDecode'](arg1);
}

export function JWTEncode(arg1, arg2, arg3) {
  return window['go']['main']['App']['JWTEncode'](arg1, arg2, arg3);
}

export function JWTVerify(arg1, arg2) {
  return window['go']['main']['App']['JWTVerify'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function VerifyKeyPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyKeyPair'](arg1, arg2, arg3);
}
